dist: focal # Ubuntu Focal 20.04
language: php
php:
  - 7.4
matrix:
  fast_finish: true
services:
  - mysql
before_install:
  - export INI=~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
  - echo memory_limit = -1 >> $INI
  - composer global require --no-progress --no-scripts --no-plugins lemurro/installer
  - export PATH=$HOME/.config/composer/vendor/bin:$PATH
install:
  - cd ~
  - lemurro new mycrm --lv=2.0 --api --skip --silent
  - mysql -e 'CREATE DATABASE IF NOT EXISTS lemurro;'
  - mysql -u root lemurro < ~/mycrm/api/database.sql
  - cd ~/mycrm/api/vendor/lemurro/api-core
  - composer install
before_script:
  - php -S 127.0.0.1:8000 -t ~/mycrm/api/public > /dev/null 2>&1 &
script:
  - php ~/mycrm/api/vendor/bin/codecept run api
  - php ~/mycrm/api/vendor/lemurro/api-core/vendor/bin/codecept run api
